server:
  port: 8000

spring:
  application:
    name: user-service
  cloud:
    config:
      uri: localhost:8888
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka