spring:
  cloud:
    config:
      retry:
        max-attempts: 30
  # 间隔乘数，默认1.1
        multiplier: 1
  # 初始重试间隔时间，默认1000ms
        initial-interval: 3000
  # 最大间隔时间，默认2000ms
        max-interval: 60000