server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shipengfish/config-repo.git
          search-paths:
            - '/{profile}'
            - '/{profile}/{application}'
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
