server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shipengfish/spring-cloud-learning.git
          search-paths:
            - '/config-repo'
            - '/{profile}'
            - '/{profile}/{application}'

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka